export { default as GeneralPage } from './GeneralPage'
export { default as ErrorPage } from './ErrorPage'
export { default as ProductsPage } from './ProductsPage'
export { default as AddProductPage } from './AddProductPage'
export { default as DeleteProductPage } from './DeleteProductPage'
export { default as WarehouseInfoPage } from './WarehouseInfoPage'